/**
 * G8 - Signals and Emissions Module
 * General Class Amateur Radio License
 */

import type { LearningModule } from '@/types/learning'

export const signalsEmissionsModule: LearningModule = {
  id: 'G8',
  examLevel: 'general',
  title: 'Signals and Emissions',
  description:
    'Understanding modulation types, signal bandwidth, mixing processes, intermodulation, and digital modes used in amateur radio communications.',
  estimatedMinutes: 45,
  sections: [
    {
      id: 'G8A',
      title: 'Modulation Types and Bandwidth',
      content: `# Modulation Types and Bandwidth

Modulation is the process of encoding information onto a carrier signal for transmission. Understanding different modulation types and their bandwidth characteristics is essential for effective amateur radio operation.

## Fundamental Modulation Types

**Amplitude Modulation (AM)** varies the instantaneous power level of the RF signal to convey information. The modulation envelope of an AM signal is the waveform created by connecting the peak values of the modulated signal. Overmodulation causes "flat-topping," which is signal distortion caused by excessive drive or speech levels, resulting in excessive bandwidth that can interfere with adjacent frequencies.

**Frequency Modulation (FM)** changes the instantaneous frequency of an RF wave to convey information. FM signals are less susceptible to noise but occupy more bandwidth than AM or SSB. **Phase Modulation (PM)** changes the phase angle of an RF signal to convey information. A reactance modulator connected to a transmitter RF amplifier stage produces phase modulation.

## Digital Modulation Schemes

**Direct Binary FSK** is generated by changing an oscillator's frequency directly with a digital control signal. In FSK signals, the two separate frequencies are identified as "mark" and "space." **QPSK (Quadrature Phase Shift Keying)** is modulation in which digital data is transmitted using 0-, 90-, 180-, and 270-degree phase shifts to represent pairs of bits.

**QPSK31** is a variant of PSK31 that is sideband sensitive, provides error correction through its encoding, and has approximately the same bandwidth as BPSK31. **FT8** uses 8-tone frequency shift keying (8-FSK) modulation, making it highly efficient for weak signal communications.

## Bandwidth Considerations

Among phone emissions, **Single Sideband (SSB)** uses the narrowest bandwidth because it transmits only one sideband and suppresses the carrier. This efficiency makes SSB the preferred mode for HF voice communications. Overmodulation is problematic because it causes excessive bandwidth, creating splatter that interferes with adjacent frequencies.

## Link Performance Metrics

A **link budget** is the sum of transmit power and antenna gains minus system losses as seen at the receiver. It helps predict whether a communication path is viable. **Link margin** is the difference between the received power level and the minimum required signal level at the input to the receiver, providing a safety margin for signal fading and other variations.
`,
      keyPoints: [
        'Amplitude modulation varies instantaneous power level of the RF signal',
        'Frequency modulation changes instantaneous frequency to convey information',
        'Phase modulation changes the phase angle of the RF signal',
        'Single sideband uses the narrowest bandwidth among phone emissions',
        'Overmodulation causes excessive bandwidth and signal distortion (flat-topping)',
      ],
      relatedQuestionIds: [
        'G8A01',
        'G8A02',
        'G8A03',
        'G8A04',
        'G8A05',
        'G8A06',
        'G8A07',
        'G8A08',
        'G8A09',
        'G8A10',
        'G8A11',
        'G8A12',
        'G8A13',
        'G8A14',
      ],
    },
    {
      id: 'G8B',
      title: 'Mixing, Intermodulation, and Bandwidth Calculations',
      content: `# Mixing, Intermodulation, and Bandwidth Calculations

Understanding how signals are processed in radio equipment, including mixing and the unwanted effects of intermodulation, is crucial for troubleshooting and optimizing amateur radio systems.

## Mixing and Heterodyning

**Heterodyning** is another term for the mixing of two RF signals. In a mixer, the **Local Oscillator (LO)** input is varied or tuned to convert signals of different frequencies to an intermediate frequency (IF). The output of a mixer contains the **sum and difference** of the Local Oscillator and RF input frequencies.

The **image response** is interference from a signal at twice the IF frequency from the desired signal. This occurs because both the desired signal and the image produce the same IF when mixed with the local oscillator. Proper receiver design includes filters to reject image frequencies.

## Frequency Multiplication

A **multiplier** is the stage in a VHF FM transmitter that generates a harmonic of a lower frequency signal to reach the desired operating frequency. When using a multiplier, the frequency deviation is also multiplied. For example, a 12.21 MHz reactance modulated oscillator in a 5 kHz deviation, 146.52 MHz FM phone transmitter would have a deviation of approximately 416.7 Hz at the oscillator (since 146.52/12.21 = 12x multiplication factor, and 5000/12 = 416.7 Hz).

## Intermodulation

**Intermodulation** is the process that combines two signals in a non-linear circuit to produce unwanted spurious outputs. **Odd-order intermodulation products** are closest to the original signal frequencies and are therefore most problematic. An example of an odd-order intermodulation product of frequencies F1 and F2 is **2F1-F2** (a third-order product).

## Bandwidth Calculations

The total bandwidth of an FM signal can be calculated using Carson's rule: BW = 2 × (deviation + maximum modulating frequency). For an FM phone transmission with 5 kHz deviation and 3 kHz modulating frequency, the total bandwidth is 2 × (5 + 3) = **16 kHz**.

**Higher symbol rates require wider bandwidth** - there is a direct relationship between transmitted symbol rate and bandwidth. This is why narrowband digital modes like PSK31 use low symbol rates to fit within limited bandwidth.

## Practical Considerations

**Matching receiver bandwidth to the operating mode** results in the best signal-to-noise ratio. Using a filter that is too wide admits unnecessary noise, while one that is too narrow cuts off part of the signal.

Knowing the **duty cycle** of your transmission mode is important because some modes have high duty cycles that could exceed the transmitter's average power rating. Digital modes and FM typically have higher duty cycles than SSB voice.
`,
      keyPoints: [
        'Heterodyning is the mixing of two RF signals producing sum and difference frequencies',
        'The local oscillator is tuned to convert different frequencies to the IF',
        'Odd-order intermodulation products (like 2F1-F2) are closest to original frequencies',
        'FM bandwidth = 2 x (deviation + max modulating frequency)',
        'Matching receiver bandwidth to operating mode provides best signal-to-noise ratio',
      ],
      relatedQuestionIds: [
        'G8B01',
        'G8B02',
        'G8B03',
        'G8B04',
        'G8B05',
        'G8B06',
        'G8B07',
        'G8B08',
        'G8B09',
        'G8B10',
        'G8B11',
        'G8B12',
        'G8B13',
      ],
    },
    {
      id: 'G8C',
      title: 'Digital Modes and Protocols',
      content: `# Digital Modes and Protocols

Digital communication modes have revolutionized amateur radio, enabling reliable contacts under challenging conditions and opening new possibilities for data transmission. Understanding these modes and their protocols is essential for modern amateur operation.

## Frequency Sharing and Digital Voice

Amateurs share channels with the unlicensed Wi-Fi service on the **2.4 GHz band**. This creates both challenges and opportunities for high-speed digital communications. **Digital voice modes** including DMR, D-STAR, and SystemFusion provide clear audio and additional features like GPS positioning and text messaging capabilities.

## Weak Signal Digital Modes

**WSPR (Weak Signal Propagation Reporter)** is used as a low-power beacon for assessing HF propagation. Stations running just a few watts can be heard across the world, making it invaluable for understanding band conditions.

**FT8** is a narrow-band digital mode that can receive signals with very low signal-to-noise ratios. An FT8 signal report of +3 means the signal-to-noise ratio is equivalent to +3 dB in a 2.5 kHz bandwidth. FT8 has become extremely popular for making contacts when bands are marginal.

## PSK31 and Varicode

**PSK31** uses **Varicode** for sending characters, where common characters use shorter bit sequences and uncommon characters use longer ones. Upper case letters use longer Varicode bit sequences and thus slow down transmission, which is why experienced operators typically use lower case. PSK31 is highly efficient, requiring only about 31 Hz of bandwidth.

## RTTY and Baudot Code

**Baudot code** is a 5-bit code with additional start and stop bits, used in traditional RTTY (radioteletype) communications. While older, RTTY remains popular for contests and casual contacts.

## FSK Signal Characteristics

In **Frequency Shift Keying (FSK)**, the two separate frequencies are identified as **mark and space**. On a waterfall display, one or more vertical lines on either side of a data mode or RTTY signal indicate **overmodulation**, which causes splatter and interference.

## Error Handling and Correction

**ARQ (Automatic Repeat reQuest)** modes use handshaking to ensure accurate data transfer. A **NAK (Negative Acknowledgment)** response requests retransmission of a packet that was received with errors. If excessive transmission attempts fail to exchange information, the connection is dropped.

**Forward Error Correction (FEC)** allows the receiver to correct data errors by transmitting redundant information with the data. This enables one-way broadcasts without the need for retransmission requests.

## Packet Radio and Networking

In packet radio, the **header** contains the routing and handling information needed to deliver the message. **Mesh network microwave nodes** provide redundancy - if one node fails, a packet may still reach its target station via an alternate node.

## Waterfall Displays

A **waterfall display** shows frequency on the horizontal axis, signal strength as intensity (brightness), and time on the vertical axis. This visualization is invaluable for identifying signals and monitoring band activity in digital modes.
`,
      keyPoints: [
        'WSPR is used as a low-power beacon for assessing HF propagation',
        'FT8 can decode signals with very low signal-to-noise ratios',
        'PSK31 uses Varicode where common characters have shorter bit sequences',
        'FSK frequencies are identified as mark and space',
        'DMR, D-STAR, and SystemFusion are digital voice modes',
      ],
      relatedQuestionIds: [
        'G8C01',
        'G8C02',
        'G8C03',
        'G8C04',
        'G8C05',
        'G8C06',
        'G8C07',
        'G8C08',
        'G8C09',
        'G8C10',
        'G8C11',
        'G8C12',
        'G8C13',
        'G8C14',
        'G8C15',
        'G8C16',
      ],
    },
  ],
}
