/**
 * T7 - Station Equipment
 * Learning module for transceivers, troubleshooting, test equipment, and practical measurements
 */

import type { LearningModule } from '@/types/learning'

export const stationEquipmentModule: LearningModule = {
  id: 'T7',
  examLevel: 'technician',
  title: 'Station Equipment',
  description:
    'Understanding transceivers, receivers, and transmitters; troubleshooting interference problems; using test equipment like oscilloscopes, multimeters, and SWR meters; and practical skills including measurements and soldering.',
  estimatedMinutes: 50,
  sections: [
    {
      id: 'T7A',
      title: 'Transceivers, Receivers, and Transmitters',
      content: `A transceiver is a device that combines both a receiver and a transmitter into a single unit, which is the most common type of amateur radio equipment today. Modern transceivers include sophisticated circuitry that allows seamless switching between transmitting and receiving. The PTT (Push-To-Talk) input is what controls this switching—when grounded, it switches the transceiver from receive mode to transmit mode, allowing you to speak into the microphone.

Inside a transceiver, several key circuits work together. An oscillator generates a signal at a specific frequency, which serves as the basis for both receiving and transmitting. A mixer is used to convert signals from one frequency to another, which is essential for superheterodyne receivers that convert incoming signals to an intermediate frequency for easier processing. When you want to add voice to your RF carrier signal, this process is called modulation—combining speech with the RF carrier to create the transmitted signal.

Receiver performance is characterized by two important specifications: sensitivity and selectivity. Sensitivity describes the receiver's ability to detect weak signals—a more sensitive receiver can hear weaker stations. Selectivity describes the receiver's ability to discriminate between multiple signals that are close in frequency, rejecting unwanted adjacent signals while passing the desired one. Both characteristics are crucial for effective amateur radio operation.

Additional equipment can enhance your station's capabilities. An RF power amplifier increases the transmitted output power from a transceiver when you need more signal strength. A transverter converts the RF input and output of a transceiver to another band, allowing you to use your existing radio on frequencies it wasn't originally designed for. An RF preamplifier is installed between the antenna and receiver to boost weak signals before they reach the receiver, improving reception of distant stations. VHF power amplifiers often have an SSB/CW-FM switch that sets the amplifier for proper operation in the selected mode, since different modes have different duty cycle and linearity requirements.`,
      keyPoints: [
        'A transceiver combines a receiver and transmitter in one unit',
        'PTT (Push-To-Talk) switches from receive to transmit when grounded',
        'Sensitivity = ability to detect weak signals; Selectivity = ability to discriminate between signals',
        'A mixer converts signals from one frequency to another; an oscillator generates signals at specific frequencies',
        'RF preamplifiers go between antenna and receiver; RF power amplifiers boost transmitter output',
      ],
      relatedQuestionIds: [
        'T7A01',
        'T7A02',
        'T7A03',
        'T7A04',
        'T7A05',
        'T7A06',
        'T7A07',
        'T7A08',
        'T7A09',
        'T7A10',
        'T7A11',
      ],
    },
    {
      id: 'T7B',
      title: 'Troubleshooting and Interference',
      content: `Radio frequency interference (RFI) can come from many sources and affect both amateur stations and consumer electronics. The three main causes of RFI are fundamental overload (when a strong signal overwhelms a receiver's front end), harmonics (unwanted signals at multiples of the transmitted frequency), and spurious emissions (unwanted signals generated by transmitter imperfections). Understanding these causes helps you diagnose and solve interference problems.

When your amateur transmissions interfere with a neighbor's radio or TV, the first step is to make sure your own station is functioning properly and doesn't cause interference to your own equipment tuned to the same channel. Fundamental overload of consumer receivers—where the amateur signal is simply too strong for the receiver to handle—can be reduced by installing a filter at the antenna input of the affected receiver to block the amateur frequencies. For cable TV interference, the first step should be ensuring all coaxial connectors are properly installed, as loose connections are a common cause of signal leakage.

Your station can also experience interference from outside sources. If a nearby commercial FM station is overloading your VHF transceiver, installing a band-reject filter can attenuate the interfering signal while passing your desired frequencies. When something in a neighbor's home causes interference to your station, work cooperatively with them to identify the offending device, politely inform them that FCC rules prohibit devices that cause harmful interference, and ensure your station meets good amateur practice standards.

Common on-air problems have identifiable causes and solutions. If you're told your FM signal is over-deviating (too much frequency swing), talk farther away from the microphone to reduce audio input. Distorted or unintelligible audio through a repeater could be caused by being slightly off frequency, low batteries, or being in a poor location with multipath or weak signal. RF feedback in a transmitter causes garbled, distorted, or unintelligible voice transmissions and typically results from RF energy getting back into audio circuits. Distorted audio caused by RF current on microphone cable shields can be cured with a ferrite choke, which blocks the RF while passing audio signals.`,
      keyPoints: [
        'RFI causes: fundamental overload, harmonics, and spurious emissions',
        'For interference to neighbors: first verify your own station works properly on that channel',
        'Fundamental overload in consumer devices is solved with a filter at THEIR antenna input',
        'Over-deviation on FM: speak farther from the microphone',
        'Ferrite chokes cure RF on microphone cables; band-reject filters block nearby FM broadcast interference',
      ],
      relatedQuestionIds: [
        'T7B01',
        'T7B02',
        'T7B03',
        'T7B04',
        'T7B05',
        'T7B06',
        'T7B07',
        'T7B08',
        'T7B09',
        'T7B10',
        'T7B11',
      ],
    },
    {
      id: 'T7C',
      title: 'Test Equipment - Dummy Loads, Antenna Analyzers, and SWR',
      content: `A dummy load is an essential piece of test equipment that allows you to test your transmitter without radiating a signal over the air. It consists of a non-inductive resistor mounted on a heat sink, designed to safely absorb and dissipate the RF power as heat. Dummy loads are typically 50 ohms to match standard amateur radio equipment impedance. Using a dummy load during testing prevents interference to other stations and allows you to troubleshoot transmitter problems without broadcasting.

Standing Wave Ratio (SWR) is a critical measurement that indicates how well your antenna system is matched to your feed line and transmitter. A perfect impedance match produces an SWR reading of 1:1, meaning all the power is being delivered to the antenna with no reflections. An SWR reading of 4:1 indicates a significant impedance mismatch, which means power is being reflected back toward the transmitter instead of being radiated. Most solid-state transmitters include protection circuitry that automatically reduces output power as SWR increases to protect the output amplifier transistors from damage caused by reflected power.

SWR can be measured using a directional wattmeter (also called an SWR meter or SWR bridge). An antenna analyzer is a more sophisticated instrument that can determine if an antenna is resonant at the desired operating frequency and provide additional information about impedance. These tools are invaluable for antenna installation and troubleshooting.

Coaxial cable is a critical part of your antenna system, and its condition affects performance. Power lost in a feed line is converted into heat, reducing the power delivered to your antenna. Moisture contamination is a leading cause of coaxial cable failure—water intrusion increases losses dramatically and can cause complete cable failure. The outer jacket of coaxial cable should be resistant to ultraviolet light because UV exposure can damage the jacket and allow water to enter. Air core coaxial cable, while having lower loss than solid dielectric types, requires special techniques to prevent moisture from entering the cable, making it more challenging to install and maintain in outdoor applications.`,
      keyPoints: [
        'Dummy load = non-inductive resistor on heat sink; prevents on-air transmission during testing',
        'SWR of 1:1 = perfect match; SWR of 4:1 = significant mismatch',
        'Solid-state transmitters reduce power at high SWR to protect output transistors',
        'Directional wattmeter measures SWR; antenna analyzer checks resonance',
        'Coaxial cable fails from moisture; UV-resistant jacket prevents water entry',
      ],
      relatedQuestionIds: [
        'T7C01',
        'T7C02',
        'T7C03',
        'T7C04',
        'T7C05',
        'T7C06',
        'T7C07',
        'T7C08',
        'T7C09',
        'T7C10',
        'T7C11',
      ],
    },
    {
      id: 'T7D',
      title: 'Practical Measurements and Soldering',
      content: `A multimeter is the most versatile piece of test equipment in any amateur's toolkit, capable of measuring voltage, resistance, and current. Understanding how to connect the meter properly is essential for accurate measurements and safety. A voltmeter (or multimeter set to voltage mode) measures electric potential and must be connected in parallel with the component being measured. An ammeter (or multimeter set to current mode) measures electric current and must be connected in series with the circuit so that current flows through the meter.

Proper use of a multimeter requires understanding its limitations and potential hazards. One common mistake that can damage a multimeter is attempting to measure voltage when the meter is set to the resistance (ohms) setting—this can destroy the meter's internal circuitry. When measuring in-circuit resistance with an ohmmeter, always ensure that the circuit is not powered, as applying external voltage to a meter in resistance mode can damage it. A multimeter can measure voltage and resistance directly; specialized equipment is needed for measurements like signal strength, noise, impedance, and reactance.

An interesting test you can perform with an ohmmeter is checking a capacitor. When connected across a large, discharged capacitor, the ohmmeter reading will show increasing resistance with time as the capacitor charges from the meter's internal battery. This behavior can help verify that a capacitor is functional.

Soldering is a fundamental skill for building and repairing amateur radio equipment. For radio and electronic applications, you should use rosin-core solder, not acid-core solder. Acid-core solder is designed for plumbing and other non-electronic applications—its corrosive flux will damage electronic components and create unreliable connections over time. Good solder joints have a bright, shiny appearance. A cold solder joint, which indicates an unreliable connection, has a characteristic rough or lumpy surface appearance. Cold joints occur when the components weren't heated sufficiently or when movement occurred during cooling, and they should be reheated and reflowed to create a proper connection.`,
      keyPoints: [
        'Voltmeter connects in parallel; ammeter connects in series',
        'Measuring voltage on resistance setting can damage a multimeter',
        'Always ensure circuit is unpowered before measuring resistance',
        'Use rosin-core solder for electronics; never use acid-core solder',
        'Good solder joints are shiny; cold joints appear rough or lumpy',
      ],
      relatedQuestionIds: [
        'T7D01',
        'T7D02',
        'T7D03',
        'T7D04',
        'T7D06',
        'T7D07',
        'T7D08',
        'T7D09',
        'T7D10',
        'T7D11',
      ],
    },
  ],
}
